version: "3"

services:
    todo-api:
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - "5000:5000"
        
    todo-app:
        build:
            context: ./TodoApp
            dockerfile: Dockerfile # Dockerfile location is relative to the build context
        ports:
            - "4000:4000"