version: "3"

services:
    todo-api:
        build:
            dockerfile: Dockerfile
            context: .
        ports:
            - "5000:5000"
        
    todo-app:
        build:
            dockerfile: Dockerfile
            context: ./TodoApp
        ports:
            - "4000:4000"